/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FullKey: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}
type Props =JSX.IntrinsicElements['group']&{
    children?:JSX.Element
    file:string
}
export function FullKey(props: Props) {
  const { nodes, materials } = useGLTF(props.file) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="FullKey"
        castShadow
        receiveShadow
        geometry={nodes.FullKey.geometry}
        material={!props.children? undefined: materials['Material.001']}
        >
        {props.children}:
        </mesh>
    </group>
  )
}

useGLTF.preload('3DModels/FullKey.glb')
