/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import Slider, { SliderProps } from './Slider'

type GLTFResult = GLTF & {
  nodes: {
    Attack_Slider: THREE.Mesh
  }
  materials: {
    Slider: THREE.MeshStandardMaterial
  }
}

export function SliderModel(props: SliderProps) {
  const { nodes, materials } = useGLTF('/3DModels/Slider.glb') as GLTFResult
  return (
    <Slider {...props} dispose={null}>
      <mesh
        name="Attack_Slider"
        castShadow
        receiveShadow
        geometry={nodes.Attack_Slider.geometry}
        material={materials.Slider}
      />
    </Slider>
  )
}

useGLTF.preload('/3DModels/Slider.glb')
