/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube011: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh
    screw: THREE.Mesh
    screw001: THREE.Mesh
    screw002: THREE.Mesh
    screw003: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Painted metal']: THREE.MeshStandardMaterial
    ['Screw material']: THREE.MeshStandardMaterial
  }
}

export function SyntheModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3DModels/Synthe.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Synthe_body002">
          <mesh
            name="Cube011"
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials.Material}
          />
          <mesh
            name="Cube011_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1.geometry}
            material={materials['Painted metal']}
          />
          <mesh
            name="Cube011_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_2.geometry}
            material={materials['Painted metal']}
          />
          <mesh
            name="screw"
            castShadow
            receiveShadow
            geometry={nodes.screw.geometry}
            material={materials['Screw material']}
            position={[-1.39, 0.507, -0.577]}
            rotation={[Math.PI / 5, 0, 0]}
            scale={0.037}
          />
          <mesh
            name="screw001"
            castShadow
            receiveShadow
            geometry={nodes.screw001.geometry}
            material={materials['Screw material']}
            position={[-1.39, -0.167, 0.36]}
            rotation={[Math.PI / 5, 0, 0]}
            scale={0.037}
          />
          <mesh
            name="screw002"
            castShadow
            receiveShadow
            geometry={nodes.screw002.geometry}
            material={materials['Screw material']}
            position={[1.39, 0.507, -0.577]}
            rotation={[Math.PI / 5, 0, 0]}
            scale={0.037}
          />
          <mesh
            name="screw003"
            castShadow
            receiveShadow
            geometry={nodes.screw003.geometry}
            material={materials['Screw material']}
            position={[1.39, -0.167, 0.36]}
            rotation={[Math.PI / 5, 0, 0]}
            scale={0.037}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3DModels/Synthe.glb')
